version: "3.9" # optional since v1.27.0
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "9000:8080"
# version: "3.7"

# services:
#   sample:
#     container_name: sample
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ".:/app"
#       - "/app/node_modules"
#     ports:
#       - 3001:3000
#     environment:
#       - CHOKIDAR_USEPOLLING=true
